version: 0.2 

phases:
  install:
    commands:
      - python --version
      - python -m pip install -r requirements.txt 

  build:
    commands:
      - python lambda_function.py   # Or your preferred build command 
      
  post_build:
    commands:
      - echo "Build complete" 

artifacts:
  files:
    - '**/*.whl'  # Example artifact pattern for wheels
